"""add token_version to developers

Revision ID: 75abe10e9cfb
Revises: 218914bb36be
Create Date: 2026-04-23 10:07:44.717805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75abe10e9cfb'
down_revision: Union[str, Sequence[str], None] = '218914bb36be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('developers', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('developers', 'token_version')
    # ### end Alembic commands ###
