"""add pool settings and fix created_at

Revision ID: cde2997ab7aa
Revises: d5b55e257210
Create Date: 2026-04-29 00:00:04.455367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde2997ab7aa'
down_revision: Union[str, Sequence[str], None] = 'd5b55e257210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('developers', 'token_version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_password_history_developer_id'), table_name='password_history', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_password_history_developer_id'), 'password_history', ['developer_id'], unique=False)
    op.alter_column('developers', 'token_version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
