"""add unique constraint to email

Revision ID: d5b55e257210
Revises: 3fe8d36df929
Create Date: 2026-04-24 21:10:18.168639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5b55e257210'
down_revision: Union[str, Sequence[str], None] = '3fe8d36df929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_developers_email', 'developers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_developers_email', 'developers', type_='unique')

    # ### end Alembic commands ###
